- debug: msg="Bhamni Apps url is {{ bahmniapps_url }}"

- name: Get bahmniapps from remote location if configured
  get_url: url={{ bahmniapps_url }}
   force=yes
   dest=/opt/bahmni-web/etc/bahmniapps.zip
   mode=0755
  register: bahmni_apps_download_result
  when: bahmniapps_url is defined

- name: unlinking /var/www/bahmniapps
  file: path=/var/www/bahmniapps state=absent
  when:
    - bahmniapps_url is defined
    - bahmni_apps_download_result.changed

- name: Removing eFMS-bahmniapps folder
  file: path=/opt/bahmni-web/etc/eFMS-bahmniapps state=absent
  when:
    - bahmniapps_url is defined
    - bahmni_apps_download_result.changed

- name: Unzip downloaded bahmniapps file
  command: unzip /opt/bahmni-web/etc/bahmniapps.zip -d /opt/bahmni-web/etc/eFMS-bahmniapps
  when:
    - bahmniapps_url is defined
    - bahmni_apps_download_result.changed

- name: Change ownership of bahmniapps files
  action: file state=directory recurse=yes path=/opt/bahmni-web/etc/eFMS-bahmniapps owner=bahmni group=bahmni
  when:
    - bahmniapps_url is defined
    - bahmni_apps_download_result.changed

- name: linking /var/www/bahmniapps to eFMS-release-84 bahmniapps
  file: src=/opt/bahmni-web/etc/eFMS-bahmniapps dest=/var/www/bahmniapps owner=bahmni group=bahmni state=link
  when:
    - bahmniapps_url is defined
    - bahmni_apps_download_result.changed
